spring:
  application:
    name: JPA-schedule
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_schedule
    username: root
    password: qwer123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
